import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Tokens exactos exportados del design system de Stitch
        // ("Ecolex Environmental Legal Intelligence")
        "inverse-primary": "#a5d0b9",
        "primary-fixed-dim": "#a5d0b9",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#5eb792",
        "on-error-container": "#93000a",
        "outline-variant": "#c1c8c2",
        "on-secondary-fixed-variant": "#005235",
        "on-error": "#ffffff",
        "on-surface": "#1b1b1b",
        "on-secondary-container": "#00734d",
        "tertiary-fixed-dim": "#7fd8b1",
        "surface-tint": "#3f6653",
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed-variant": "#005139",
        "on-secondary-fixed": "#002113",
        "inverse-on-surface": "#f3f0ef",
        error: "#ba1a1a",
        "on-background": "#1b1b1b",
        "surface-bright": "#fcf9f8",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#414844",
        "surface-container-lowest": "#ffffff",
        background: "#fcf9f8",
        "primary-fixed": "#c1ecd4",
        "surface-container-high": "#eae7e7",
        "on-tertiary-fixed": "#002115",
        tertiary: "#002d1e",
        primary: "#012d1d",
        "on-primary-fixed-variant": "#274e3d",
        "secondary-fixed": "#92f7c3",
        "surface-container": "#f0eded",
        "on-primary-container": "#86af99",
        "tertiary-fixed": "#9af5cc",
        "inverse-surface": "#313030",
        "surface-variant": "#e5e2e1",
        "secondary-container": "#92f7c3",
        "primary-container": "#1b4332",
        secondary: "#006c48",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#75daa8",
        "surface-container-highest": "#e5e2e1",
        "on-primary-fixed": "#002114",
        "tertiary-container": "#004530",
        outline: "#717973",
        // Paleta de marca explicita (nombres literales pedidos para Ecolex)
        "verde-oscuro": "#1B4332",
        crema: "#F8F5F0",
        sage: "#52B788",
        carbon: "#1C1C1C",
        blanco: "#FFFFFF",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "1.5rem",
        "margin-mobile": "1rem",
        margin: "2rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "title-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "label-lg": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" },
        ],
        "display-lg": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "30px",
          { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "700" },
        ],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
